export * from './layout'
export * from'./navbar'
export * from './hero'
export * from './stats'
export * from './services'
export * from './appointment'
export * from './testimonials'
export * from './teams'
export * from './faq'
export * from './departments'
export * from './blog'
export * from './brands'
export * from './news'
export * from './other'